# Generated by Django 2.1 on 2019-05-13 23:00

from django.db import migrations, models
import django.db.models.deletion
import main.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email адрес')),
                ('name', models.CharField(blank=True, default='', max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Менеджер', 'Менеджер'), ('Администратор', 'Администратор'), ('Журналист', 'Журналист')], db_index=True, default='Администратор', max_length=100, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Confidant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='ФИО')),
                ('description', models.TextField(blank=True, default='', max_length=2550, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Доверенное лицо',
                'verbose_name_plural': 'Доверенные лица',
            },
        ),
        migrations.CreateModel(
            name='ConfidantMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=main.models.uploaded_filename)),
                ('confidant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confidant', to='main.Confidant')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='Контакт')),
                ('location', models.CharField(max_length=255, verbose_name='Место жительства')),
                ('career', models.CharField(blank=True, max_length=255, verbose_name='Род деятельности')),
                ('wish_type', models.CharField(max_length=255, verbose_name='Пожелание/Предложение')),
                ('body', models.TextField(max_length=2550, verbose_name='Текст')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('isShown', models.BooleanField(default=False, verbose_name='Показать на сайте')),
                ('type', models.CharField(choices=[('Пожелание', 'Пожелание'), ('Предложение', 'Предложение')], db_index=True, default='Пожелание', max_length=100, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Пожелание',
                'verbose_name_plural': 'Пожелания',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Медиатека',
                'verbose_name_plural': 'Медиатека',
            },
        ),
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=main.models.uploaded_filename)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='main.Gallery')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='GalleryVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=main.models.uploaded_filename)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='main.Gallery')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (Рус)')),
                ('title_kz', models.CharField(max_length=255, verbose_name='Название (Каз)')),
                ('description_ru', models.TextField(max_length=140, verbose_name='Описание (Рус)')),
                ('description_kz', models.TextField(max_length=140, verbose_name='Описание (Каз)')),
                ('body_ru', tinymce.models.HTMLField()),
                ('body_kz', tinymce.models.HTMLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=main.models.uploaded_filename)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='main.News')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='NewsVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=main.models.uploaded_filename)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new', to='main.News')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='ФИО')),
                ('date_from', models.DateField(verbose_name='Дата начала')),
                ('date_to', models.DateField(verbose_name='Дата окончания')),
                ('children_num', models.IntegerField(db_index=True, default=0, verbose_name='Кол-во детей')),
                ('with_meal', models.BooleanField(default=False, verbose_name='Питание')),
                ('guest_num', models.IntegerField(db_index=True, default=1, verbose_name='Кол-во гостей')),
                ('final_cost', models.IntegerField(db_index=True, default=1, verbose_name='Окончательная цена')),
                ('prepayment', models.IntegerField(db_index=True, default=0, verbose_name='Предоплата')),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('telephone', models.CharField(db_index=True, max_length=15, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['room', 'date_from', 'date_to'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', max_length=2550, verbose_name='Описание')),
                ('price', models.IntegerField(db_index=True, default=1, verbose_name='Цена')),
                ('prior_price', models.IntegerField(db_index=True, default=1, verbose_name='Высокая цена')),
                ('lake_view', models.BooleanField(default=False, verbose_name='Вид на озеро')),
                ('type', models.CharField(choices=[('Эконом', 'Эконом'), ('Бизнес', 'Бизнес'), ('Премиум', 'Премиум')], db_index=True, default='Эконом', max_length=100, verbose_name='Тип')),
                ('count', models.IntegerField(db_index=True, default=1, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='RoomMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=main.models.uploaded_filename)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='main.Room')),
            ],
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Видеогалерея',
                'verbose_name_plural': 'Видеогалерея',
            },
        ),
        migrations.CreateModel(
            name='VideoGalleryVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=main.models.uploaded_filename)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='main.VideoGallery')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.Room'),
        ),
    ]
