# Generated by Django 2.1 on 2019-05-14 20:20

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body_kz',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Текст (Каз)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Текст (Рус)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_kz',
            field=models.TextField(blank=True, max_length=140, null=True, verbose_name='Описание (Каз)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=models.TextField(blank=True, max_length=140, null=True, verbose_name='Описание (Рус)'),
        ),
    ]
