# Generated by Django 2.1 on 2019-05-14 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190515_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerymedia',
            name='gallery',
        ),
        migrations.AddField(
            model_name='gallerymedia',
            name='galleries',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='main.Gallery'),
            preserve_default=False,
        ),
    ]
