# Generated by Django 2.1 on 2019-05-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190515_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (Каз)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (Рус)'),
        ),
    ]
