# Generated by Django 2.1 on 2019-05-21 17:46

from django.db import migrations, models
import django.db.models.deletion
import main.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190521_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsENG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=140, null=True, verbose_name='Описание')),
                ('body', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Текст')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость (ENG)',
                'verbose_name_plural': 'Новости (ENG)',
            },
        ),
        migrations.CreateModel(
            name='NewsENGMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=main.models.uploaded_filename)),
                ('newsENG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsENG', to='main.NewsENG')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='NewsENGVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=main.models.uploaded_filename)),
                ('newENG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newENG', to='main.NewsENG')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='NewsKZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=140, null=True, verbose_name='Описание')),
                ('body', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Текст')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость (Kaz)',
                'verbose_name_plural': 'Новости (Kaz)',
            },
        ),
        migrations.CreateModel(
            name='NewsKZMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=main.models.uploaded_filename)),
                ('newsKZ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsKZ', to='main.NewsKZ')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='NewsKZVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=main.models.uploaded_filename)),
                ('newKZ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newKZ', to='main.NewsKZ')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='NewsRU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=140, null=True, verbose_name='Описание')),
                ('body', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Текст')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость (Rus)',
                'verbose_name_plural': 'Новости (Rus)',
            },
        ),
        migrations.CreateModel(
            name='NewsRUMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=main.models.uploaded_filename)),
                ('newsRU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsRU', to='main.NewsRU')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='NewsRUVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=main.models.uploaded_filename)),
                ('newRU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newRU', to='main.NewsRU')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
