# Generated by Django 2.1 on 2019-05-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_newseng_newsengmedia_newsengvideo_newskz_newskzmedia_newskzvideo_newsru_newsrumedia_newsruvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newseng',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='newskz',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='newsru',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
    ]
