# Generated by Django 2.1 on 2019-05-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190523_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Место жительства'),
        ),
    ]
