# Generated by Django 2.1 on 2019-05-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190525_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newseng',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
    ]
