# Generated by Django 2.1 on 2019-06-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190528_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confidantmedia',
            name='confidant',
        ),
        migrations.RemoveField(
            model_name='gallerymedia',
            name='galleries',
        ),
        migrations.RemoveField(
            model_name='galleryvideo',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='newsengmedia',
            name='newsENG',
        ),
        migrations.RemoveField(
            model_name='newsengvideo',
            name='newENG',
        ),
        migrations.RemoveField(
            model_name='newsmedia',
            name='news',
        ),
        migrations.RemoveField(
            model_name='newsrumedia',
            name='newsRU',
        ),
        migrations.RemoveField(
            model_name='newsruvideo',
            name='newRU',
        ),
        migrations.RemoveField(
            model_name='newsvideo',
            name='new',
        ),
        migrations.RemoveField(
            model_name='videogalleryvideo',
            name='gallery',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Диспетчер', 'Диспетчер'), ('Администратор', 'Администратор')], db_index=True, default='Администратор', max_length=100, verbose_name='Тип пользователя'),
        ),
        migrations.DeleteModel(
            name='Confidant',
        ),
        migrations.DeleteModel(
            name='ConfidantMedia',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='GalleryMedia',
        ),
        migrations.DeleteModel(
            name='GalleryVideo',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='NewsENG',
        ),
        migrations.DeleteModel(
            name='NewsENGMedia',
        ),
        migrations.DeleteModel(
            name='NewsENGVideo',
        ),
        migrations.DeleteModel(
            name='NewsMedia',
        ),
        migrations.DeleteModel(
            name='NewsRU',
        ),
        migrations.DeleteModel(
            name='NewsRUMedia',
        ),
        migrations.DeleteModel(
            name='NewsRUVideo',
        ),
        migrations.DeleteModel(
            name='NewsVideo',
        ),
        migrations.DeleteModel(
            name='VideoGallery',
        ),
        migrations.DeleteModel(
            name='VideoGalleryVideo',
        ),
    ]
