# Generated by Django 2.1 on 2019-06-18 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190618_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Месторождение',
                'verbose_name_plural': 'Месторождения',
            },
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='main.Field')),
            ],
        ),
        migrations.CreateModel(
            name='WellMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluid', models.FloatField(db_index=True, default=0, verbose_name='Замерная жидкость')),
                ('teh_rej_fluid', models.FloatField(db_index=True, default=0, verbose_name='Техрежим жидкости')),
                ('teh_rej_oil', models.FloatField(db_index=True, default=0, verbose_name='Техрежим нефти')),
                ('teh_rej_water', models.FloatField(db_index=True, default=0, verbose_name='Обводненность')),
                ('timestamp', models.DateTimeField(verbose_name='Дата замера')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='main.Well')),
            ],
        ),
    ]
