# Generated by Django 2.1 on 2019-06-18 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_field_well_wellmatrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_balance', models.FloatField(db_index=True, default=0, verbose_name='Автомобильные весы')),
                ('ansagan_balance', models.FloatField(db_index=True, default=0, verbose_name='Весы по Ансаган')),
                ('timestamp', models.DateTimeField(verbose_name='Дата замера')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Field')),
            ],
            options={
                'verbose_name': 'Баланс по Месторождениям',
            },
        ),
        migrations.AlterModelOptions(
            name='well',
            options={'verbose_name': 'Скважина', 'verbose_name_plural': 'Скважины'},
        ),
        migrations.AlterModelOptions(
            name='wellmatrix',
            options={'verbose_name': 'Матрица скважин'},
        ),
    ]
