# Generated by Django 2.1 on 2019-06-18 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190618_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldbalance',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bal_fields', to='main.Field'),
        ),
    ]
