# Generated by Django 2.1 on 2019-06-27 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190618_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(db_index=True, default=0, verbose_name='Запрашиваемая сумма')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('approved', models.BooleanField(default=False, verbose_name='Одобрено администратором')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.RemoveField(
            model_name='fieldbalance',
            name='field',
        ),
        migrations.RemoveField(
            model_name='newskzmedia',
            name='newsKZ',
        ),
        migrations.RemoveField(
            model_name='newskzvideo',
            name='newKZ',
        ),
        migrations.RemoveField(
            model_name='order',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roommedia',
            name='room',
        ),
        migrations.RemoveField(
            model_name='well',
            name='field',
        ),
        migrations.RemoveField(
            model_name='wellmatrix',
            name='well',
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Клиент', 'Клиент'), ('Администратор', 'Администратор')], db_index=True, default='Администратор', max_length=100, verbose_name='Тип пользователя'),
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='FieldBalance',
        ),
        migrations.DeleteModel(
            name='NewsKZ',
        ),
        migrations.DeleteModel(
            name='NewsKZMedia',
        ),
        migrations.DeleteModel(
            name='NewsKZVideo',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomMedia',
        ),
        migrations.DeleteModel(
            name='Well',
        ),
        migrations.DeleteModel(
            name='WellMatrix',
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='ФИО заявителя'),
        ),
    ]
