# Generated by Django 2.1 on 2019-06-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_user_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='noticed',
            field=models.BooleanField(default=False, verbose_name='Отправлено уведомление'),
        ),
    ]
