# Generated by Django 2.1 on 2019-07-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_application_noticed'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comission',
            field=models.FloatField(db_index=True, default=0, verbose_name='Комиссия'),
        ),
        migrations.AddField(
            model_name='application',
            name='comission_to_job',
            field=models.FloatField(db_index=True, default=0, verbose_name='Комиссия работодателя'),
        ),
    ]
